name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #Checkout the Source cod from the latest commit
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      #We need to install NPM so that we can install SFDX CLI tools
      - name: Install NPM
        run: |
          npm install
      #Install the SFDX CLI using npm command
      - name: Install the SFDX CLI
        run: |
          npm install sfdx-cli --global
          sfdx force --help